const signerPreferenceKey='ESC_TURBINE_SIGNER_PREFS_V1',signerDirectoryKey='ESC_TURBINE_SIGNER_DIRECTORY_V1';
let signerDirectory=[],signerPreferences={};
try{const d=JSON.parse(localStorage.getItem(signerDirectoryKey)||'[]'),p=JSON.parse(localStorage.getItem(signerPreferenceKey)||'{}');if(Array.isArray(d))signerDirectory=d.filter(i=>i&&typeof i.name==='string'&&typeof i.position==='string');if(p&&typeof p==='object')signerPreferences=p;}catch{}
function storeSignerPreferences(){try{localStorage.setItem(signerDirectoryKey,JSON.stringify(signerDirectory));localStorage.setItem(signerPreferenceKey,JSON.stringify(signerPreferences));}catch{status('จำรายชื่อไม่ได้ กรุณาตรวจพื้นที่เก็บข้อมูลของเบราว์เซอร์');}}
function addDirectory(name,position){if(name&&!signerDirectory.some(i=>i.name===name&&i.position===position))signerDirectory.push({name,position});}
for(const id of Object.keys(roles)){const oldName=$(id),oldPosition=$('position_'+id),current={name:oldName.value,position:oldPosition.value};const chosen=current.name||current.position?current:signerPreferences[id]||current;addDirectory(chosen.name,chosen.position||'');const name=document.createElement('select'),position=document.createElement('select');name.id=id;position.id='position_'+id;name.dataset.record='true';position.dataset.record='true';name.setAttribute('aria-label','ชื่อ '+roles[id]);position.setAttribute('aria-label','ตำแหน่ง '+roles[id]);oldName.replaceWith(name);oldPosition.replaceWith(position);signerPreferences[id]={name:chosen.name||'',position:chosen.position||''};}
function populateSignerOptions(id,chosen){const name=$(id),position=$('position_'+id);name.replaceChildren(new Option('เลือกชื่อผู้เซ็น',''));[...new Set(signerDirectory.map(i=>i.name).concat(chosen.name||[]))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'th')).forEach(n=>name.append(new Option(n,n)));position.replaceChildren(new Option('เลือกตำแหน่ง',''));[...new Set(signerDirectory.filter(i=>i.name===chosen.name).map(i=>i.position).concat(chosen.position||[]))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'th')).forEach(p=>position.append(new Option(p,p)));name.value=chosen.name||'';position.value=chosen.position||'';name.disabled=position.disabled=isLocked();}
function restoreSignerSelections(){for(const id of Object.keys(roles))populateSignerOptions(id,signerPreferences[id]||{name:'',position:''});renderSignatures();updateSigningGate();}
restoreSignerSelections();storeSignerPreferences();
for(const id of Object.keys(roles)){
$(id).onchange=()=>{if(isLocked())return;const name=$(id).value,positions=[...new Set(signerDirectory.filter(i=>i.name===name).map(i=>i.position))];signerPreferences[id]={name,position:positions.length===1?positions[0]:''};populateSignerOptions(id,signerPreferences[id]);storeSignerPreferences();renderSignatures();save();updateSigningGate();};
$('position_'+id).onchange=()=>{if(isLocked())return;signerPreferences[id]={name:$(id).value,position:$('position_'+id).value};storeSignerPreferences();renderSignatures();save();updateSigningGate();};}
const manageSigners=document.createElement('button');manageSigners.textContent='จัดการรายชื่อผู้เซ็น';document.querySelector('.toolbar').append(manageSigners);
const signerDialog=document.createElement('dialog');signerDialog.style.cssText='width:min(480px,94vw);border:1px solid #c5d5c9;border-radius:10px;padding:22px';signerDialog.innerHTML='<h2>เพิ่มชื่อและตำแหน่ง</h2><form id="signerForm"><label>ชื่อผู้เซ็น<input id="newSignerName" data-editor="true" required></label><label>ตำแหน่ง<input id="newSignerPosition" data-editor="true" required></label><p class="hint">รายชื่อเก็บในเบราว์เซอร์นี้ เมื่อเลือกชื่อ ระบบจะเลือกตำแหน่งให้หากมีตำแหน่งเดียว</p><button class="primary" type="submit">เพิ่มรายชื่อ</button><button type="button" id="closeSignerDialog">ปิด</button></form><p id="signerList"></p>';document.body.append(signerDialog);
manageSigners.onclick=()=>{$('signerList').textContent=signerDirectory.map(i=>i.name+' — '+i.position).join(' / ');$('signerForm').reset();signerDialog.showModal();};$('closeSignerDialog').onclick=()=>signerDialog.close();
$('signerForm').onsubmit=e=>{e.preventDefault();const name=$('newSignerName').value.trim(),position=$('newSignerPosition').value.trim();if(!name||!position)return;addDirectory(name,position);storeSignerPreferences();for(const id of Object.keys(roles))populateSignerOptions(id,{name:$(id).value,position:$('position_'+id).value});$('signerList').textContent=signerDirectory.map(i=>i.name+' — '+i.position).join(' / ');$('signerForm').reset();status('เพิ่มรายชื่อแล้ว เลือกชื่อในช่องผู้เซ็นได้');};
const signerReset=$('reset').onclick;$('reset').onclick=()=>{signerReset();restoreSignerSelections();};
const signerLock=updateLock;updateLock=function(){signerLock();for(const id of Object.keys(roles))$(id).disabled=$('position_'+id).disabled=isLocked();};
const signerApply=apply;apply=function(data){if(isLocked())return signerApply(data);for(const id of Object.keys(roles)){const name=data.values?.[id],position=data.values?.['position_'+id];if(typeof name==='string'){addDirectory(name,typeof position==='string'?position:'');populateSignerOptions(id,{name,position:position||''});}}signerApply(data);for(const id of Object.keys(roles))signerPreferences[id]={name:$(id).value,position:$('position_'+id).value};storeSignerPreferences();updateLock();};
const signerStyle=document.createElement('style');signerStyle.textContent='.sigcard select{display:block;width:100%;margin-top:6px;font-family:"Sarabun Web",sans-serif;font-size:16px;padding:10px;min-height:44px}#signerForm label{display:block;margin:12px 0}#signerForm input{margin-top:6px}#signerList{font-size:13px;line-height:1.7}@media print{.sigcard select{display:none}}';document.head.append(signerStyle);
// Table editor: edits are staged until the user saves the entire directory.
signerDialog.style.width='min(900px,96vw)';signerDialog.style.maxHeight='90vh';signerDialog.style.overflow='auto';
signerDialog.innerHTML='<h2>จัดการรายชื่อผู้เซ็น</h2><p class="hint">เพิ่มหลายแถว แก้ไข หรือลบ แล้วบันทึกทั้งหมดพร้อมกัน ชื่อที่เลือกไว้ในเอกสารเดิมจะยังคงอยู่</p><div class="entryactions"><button id="addSignerRow" class="primary">＋ เพิ่มแถว</button><button id="editSignerRows">แก้ไขข้อมูล</button></div><div class="signerTableWrap"><table id="signerEditor"><thead><tr><th>ลำดับ</th><th>ชื่อผู้เซ็น</th><th>ตำแหน่ง</th><th>จัดการ</th></tr></thead><tbody></tbody></table></div><p id="signerEditorMessage" role="status"></p><div class="entryactions"><button id="saveSignerRows" class="primary">บันทึกทั้งหมด</button><button id="cancelSignerRows">ยกเลิก / ปิด</button></div>';
let signerDraft=[];
function renderSignerRows(){const body=$('signerEditor').querySelector('tbody');body.replaceChildren();signerDraft.forEach((row,index)=>{const tr=document.createElement('tr'),num=document.createElement('td');num.textContent=index+1;tr.append(num);for(const field of ['name','position']){const td=document.createElement('td'),input=document.createElement('input');input.dataset.editor='true';input.value=row[field];input.maxLength=180;input.placeholder=field==='name'?'ชื่อผู้เซ็น':'ตำแหน่ง';input.setAttribute('aria-label',(field==='name'?'ชื่อ':'ตำแหน่ง')+' แถว '+(index+1));input.readOnly=!row.editing;input.oninput=()=>{row[field]=input.value;};td.append(input);tr.append(td);}const actions=document.createElement('td'),edit=document.createElement('button'),remove=document.createElement('button');edit.type=remove.type='button';edit.textContent=row.editing?'เสร็จ':'แก้ไข';edit.onclick=()=>{row.editing=!row.editing;renderSignerRows();};remove.textContent='ลบ';remove.onclick=()=>{if((row.name||row.position)&&!confirm('ลบรายการ '+(row.name||'แถวนี้')+' จากตาราง?'))return;signerDraft.splice(index,1);renderSignerRows();};actions.append(edit,remove);tr.append(actions);body.append(tr);});if(!signerDraft.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.textContent='ยังไม่มีรายชื่อ กดเพิ่มแถวเพื่อเริ่ม';tr.append(td);body.append(tr);}}
manageSigners.onclick=()=>{signerDraft=signerDirectory.map(i=>({...i,editing:false}));$('signerEditorMessage').textContent='';renderSignerRows();signerDialog.showModal();};
$('addSignerRow').onclick=()=>{signerDraft.push({name:'',position:'',editing:true});renderSignerRows();$('signerEditor').querySelector('tbody tr:last-child input')?.focus();};
$('editSignerRows').onclick=()=>{signerDraft.forEach(r=>r.editing=true);renderSignerRows();};
$('cancelSignerRows').onclick=()=>signerDialog.close();
$('saveSignerRows').onclick=()=>{const rows=signerDraft.map(r=>({name:r.name.trim(),position:r.position.trim()})).filter(r=>r.name||r.position);if(rows.some(r=>!r.name||!r.position)){$('signerEditorMessage').textContent='กรอกชื่อและตำแหน่งให้ครบทุกแถว หรือกดลบแถวที่ไม่ใช้';return;}const unique=[];for(const row of rows)if(!unique.some(i=>i.name===row.name&&i.position===row.position))unique.push(row);try{localStorage.setItem(signerDirectoryKey,JSON.stringify(unique));}catch{$('signerEditorMessage').textContent='บันทึกไม่สำเร็จ กรุณาตรวจพื้นที่เก็บข้อมูล';return;}signerDirectory=unique;for(const id of Object.keys(roles))populateSignerOptions(id,{name:$(id).value,position:$('position_'+id).value});updateSigningGate();$('signerEditorMessage').textContent='บันทึกแล้ว '+unique.length+' รายการ';status('บันทึกตารางรายชื่อแล้ว '+unique.length+' รายการ');signerDraft=unique.map(r=>({...r,editing:false}));renderSignerRows();};
const tableStyle=document.createElement('style');tableStyle.textContent='.signerTableWrap{overflow:auto;margin:16px 0}#signerEditor{width:100%;min-width:560px;table-layout:auto;font-size:14px;border-collapse:collapse}#signerEditor th,#signerEditor td{padding:8px;border:1px solid #c8d8cd;text-align:left;position:static}#signerEditor th{background:#eaf3ec}#signerEditor input{font-size:16px;min-width:130px;padding:10px;min-height:44px}#signerEditor input[readonly]{background:#f3f6f4}#signerEditor td:first-child{width:50px}#signerEditor td:last-child{white-space:nowrap;width:150px}#signerEditor button{font-size:13px;padding:8px;min-height:44px;margin-right:5px}#signerEditorMessage{color:#a13b22;font-size:14px}';document.head.append(tableStyle);
updateLock();
