// One-page A4 landscape PDF, rendered locally with Sarabun; no server upload.
const pdfButton=document.createElement('button');pdfButton.id='savePDF';pdfButton.textContent='บันทึก PDF';$('print').before(pdfButton);$('print').textContent='พิมพ์';
function makePDF(jpeg,w,h){const enc=new TextEncoder(),chunks=[];let size=0;const offsets=[0];const put=s=>{const bytes=typeof s==='string'?enc.encode(s):s;chunks.push(bytes);size+=bytes.length;};put('%PDF-1.4\n');const obj=(id,body)=>{offsets[id]=size;put(id+' 0 obj\n'+body+'\nendobj\n');};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');obj(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 841.89 595.28] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>');offsets[4]=size;put('4 0 obj\n<< /Type /XObject /Subtype /Image /Width '+w+' /Height '+h+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+jpeg.length+' >>\nstream\n');put(jpeg);put('\nendstream\nendobj\n');const content='q 841.89 0 0 595.28 0 0 cm /Im0 Do Q';obj(5,'<< /Length '+enc.encode(content).length+' >>\nstream\n'+content+'\nendstream');const xref=size;put('xref\n0 6\n0000000000 65535 f \n');for(let i=1;i<=5;i++)put(String(offsets[i]).padStart(10,'0')+' 00000 n \n');put('trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF');return new Blob(chunks,{type:'application/pdf'});}
pdfButton.onclick=async()=>{pdfButton.disabled=true;try{await document.fonts.ready;renderSignatures();const c=document.createElement('canvas');c.width=3000;c.height=2121;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);const x=65,width=2870;function text(s,px,py,size=22,bold=false,align='left',max){ctx.font=(bold?'bold ':'')+size+'px "Sarabun Web"';ctx.fillStyle='#183c27';ctx.textAlign=align;ctx.fillText(String(s),px,py,max);}
text('บริษัท น้ำตาลและอ้อยตะวันออก จำกัด (มหาชน) สาขาวังสมบูรณ์',x,65,25);text('บันทึกคุณภาพ รายงานสภาพการทำงานของเครื่องเทอร์ไบน์',x,116,38,true);text('FM-ML01-ML-02 • Rev.01',x+width,65,22,false,'right');ctx.strokeStyle='#809a86';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,136);ctx.lineTo(x+width,136);ctx.stroke();
let date=$('date').value;if(date)date=new Date(date+'T12:00:00').toLocaleDateString('th-TH');text('วันที่ '+date+'    ปีการผลิต '+$('year').value+'    ฝ่าย '+$('department').value+'    แผนก '+$('section').value+'    เครื่อง '+$('machine').value,x,183,23,false,'left',width);if(typeof demoMode!=='undefined'&&demoMode)text('DEMO: ตัวเลขสาธิต ไม่ใช่ผลตรวจจริง',x+width,215,20,true,'right');
const top=232,header=145,row=54,timeW=100,noteW=280,colW=(width-timeW-noteW)/fields.length;function box(px,py,w,h,color){ctx.fillStyle=color;ctx.fillRect(px,py,w,h);ctx.strokeStyle='#9bab9d';ctx.lineWidth=1;ctx.strokeRect(px,py,w,h);}function wrap(s,px,py,w,size=17){ctx.font=size+'px "Sarabun Web"';let line='',lines=[];for(const char of s){if(ctx.measureText(line+char).width>w-8){lines.push(line);line=char;}else line+=char;}lines.push(line);lines.slice(0,3).forEach((l,i)=>text(l,px+w/2,py+i*(size+3),size,false,'center',w-5));}
box(x,top,timeW,header,'#e8f0e9');text('เวลา',x+timeW/2,top+70,20,true,'center');fields.forEach((f,i)=>{const px=x+timeW+i*colW;box(px,top,colW,header,'#e8f0e9');wrap(f[0],px,top+25,colW,16);wrap(f[1],px,top+57,colW,17);text(f[3],px+colW/2,top+116,16,false,'center',colW-5);text(f[2],px+colW/2,top+137,15,false,'center',colW-5);});box(x+width-noteW,top,noteW,header,'#e8f0e9');text('หมายเหตุ / ปัญหา / การแก้ไข',x+width-noteW/2,top+70,18,true,'center',noteW-10);
times.forEach((t,r)=>{const py=top+header+r*row;box(x,py,timeW,row,'#edf3ed');text(t,x+timeW/2,py+35,18,true,'center',timeW-8);fields.forEach((f,i)=>{const px=x+timeW+i*colW;box(px,py,colW,row,r%2?'#f5f8f4':'#fff');text($('v'+r+'_'+i).value,px+colW/2,py+35,18,false,'center',colW-5);});box(x+width-noteW,py,noteW,row,r%2?'#f5f8f4':'#fff');wrap($('note'+r).value,x+width-noteW,py+20,noteW,15);});
const sy=top+header+24*row+25,gap=18,sw=(width-4*gap)/5;Object.keys(roles).forEach((id,i)=>{const px=x+i*(sw+gap);box(px,sy,sw,310,'#fff');text(roles[id],px+sw/2,sy+32,21,true,'center',sw-15);const canvas=$('preview_'+id).querySelector('canvas');if(canvas)ctx.drawImage(canvas,px+12,sy+50,sw-24,248);});text('โรงงาน: 1573 หมู่ 1 ต.วังใหม่ อ.วังสมบูรณ์ จ.สระแก้ว 27250 • โทรศัพท์ 092-2573931, 086-3951210',x,2063,19);text('FM-ML01-ML-02 (Rev.01) 20/02/2564',x+width,2063,19,false,'right');
const raw=atob(c.toDataURL('image/jpeg',.95).split(',')[1]);const jpeg=Uint8Array.from(raw,ch=>ch.charCodeAt(0));const url=URL.createObjectURL(makePDF(jpeg,c.width,c.height));const a=document.createElement('a');a.href=url;a.download='FM-ML01-ML-02_'+($('date').value||'record')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('ดาวน์โหลด PDF แล้ว');}catch(e){status('สร้าง PDF ไม่สำเร็จ: '+e.message);}finally{pdfButton.disabled=false;}};
