const demoNotice=document.createElement('p');demoNotice.style.cssText='padding:12px;background:#fff1ca;border:1px solid #d5ad43;border-radius:6px';demoNotice.textContent='DEMO: ตัวเลขตัวอย่างสำหรับสาธิต ไม่ใช่ผลตรวจเครื่องจริง';demoNotice.hidden=true;document.querySelector('.sheet').prepend(demoNotice);
demoNotice.className='demoNotice';
const demoStyle=document.createElement('style');demoStyle.textContent='@media print{.demoNotice{font-size:7px!important;margin:0 0 1mm!important;padding:1mm!important;line-height:1!important}tbody tr{height:4mm!important}td input,td textarea{height:3.8mm!important}header h1{line-height:1.1!important}header p{line-height:1!important}.sigcard input{line-height:1!important}}';document.head.append(demoStyle);
let demoMode=false;
const demoButton=document.createElement('button');demoButton.textContent='กรอกตัวเลข Demo';demoButton.type='button';document.querySelector('.toolbar').append(demoButton);
const signingNotice=document.createElement('p');signingNotice.className='hint';$('signatures').before(signingNotice);
function missingData(){const missing=[];for(const id of ['date','year','department','section','machine'])if(!$(id).value.trim())missing.push(id);let count=0;document.querySelectorAll('#table input[type=number]').forEach(el=>{if(el.value===''||!el.validity.valid||!Number.isFinite(Number(el.value)))count++;});return {missing,count};}
function signingReady(){const m=missingData();return !m.count&&!m.missing.length;}
function priorSignaturesComplete(id){if(id==='recorder1'||id==='recorder2')return true;if(id==='supervisor1')return !!signatureData.recorder1;if(id==='supervisor2')return !!signatureData.recorder2;if(id==='approver')return !!signatureData.recorder1&&!!signatureData.supervisor1&&!!signatureData.recorder2&&!!signatureData.supervisor2;return true;}
function signatureStepHint(id){if(id==='supervisor1')return 'รอผู้บันทึกกะ 1 เซ็นก่อน';if(id==='supervisor2')return 'รอผู้บันทึกกะ 2 เซ็นก่อน (ห้ามเซ็นข้ามกะ)';if(id==='approver')return 'รอผู้บันทึกและหัวหน้ากะทั้ง 2 กะเซ็นครบ';return 'ขั้นที่ 1: ผู้บันทึกประจำกะ';}
function updateSigningGate(){const m=missingData(),ready=signingReady();signingNotice.textContent=ready?'ลำดับการเซ็น: กะ 1 (ผู้บันทึก → หัวหน้ากะ) | กะ 2 (ผู้บันทึก → หัวหน้ากะ) → ผู้รับรอง/หัวหน้าแผนก':'เปิดหน้าเซ็นได้เมื่อหัวฟอร์มครบและตัวเลขครบ 624 ช่อง • ยังขาด '+m.count+' ค่า และข้อมูลหัวฟอร์ม '+m.missing.length+' ช่อง';$('signatures').querySelectorAll('[data-sign]').forEach(b=>{const id=b.dataset.sign,prior=priorSignaturesComplete(id);b.disabled=isLocked()||!ready||!prior||!$(id).value.trim()||!$('position_'+id).value.trim();b.textContent=signatureData[id]?'เซ็นใหม่':prior?'เซ็นชื่อ':'รอลำดับก่อนหน้า';b.title=prior?'กรอกชื่อและตำแหน่งก่อนเซ็น':signatureStepHint(id);let hint=b.closest('.sigcard').querySelector('.stepHint');if(!hint){hint=document.createElement('p');hint.className='stepHint hint';b.closest('.sigcard').append(hint);}hint.textContent=signatureData[id]?'เซ็นแล้ว':prior?'พร้อมเซ็นเมื่อกรอกข้อมูลครบ':signatureStepHint(id);});demoButton.disabled=isLocked();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-sign]');if(b&&(!signingReady()||!priorSignaturesComplete(b.dataset.sign)||!$(b.dataset.sign).value.trim()||!$('position_'+b.dataset.sign).value.trim())){e.preventDefault();e.stopImmediatePropagation();alert(!priorSignaturesComplete(b.dataset.sign)?signatureStepHint(b.dataset.sign):'กรอกข้อมูลหัวฟอร์ม ตัวเลขทุกชั่วโมง และชื่อ/ตำแหน่งผู้เซ็นให้ครบก่อน');}},true);
// Changing an earlier approval invalidates dependent approvals.
document.addEventListener('click',e=>{const button=e.target.closest('[data-remove-sign]');if(!button)return;const id=button.dataset.removeSign;const before=signatureData[id];setTimeout(()=>{if(before&&!signatureData[id]){if(id==='recorder1'){delete signatureData.supervisor1;delete signatureData.approver;}else if(id==='recorder2'){delete signatureData.supervisor2;delete signatureData.approver;}else if(id==='supervisor1'||id==='supervisor2')delete signatureData.approver;renderSignatures();save();updateSigningGate();}});},true);
const sequentialConfirm=$('confirmSig').onclick;$('confirmSig').onclick=async()=>{if(!priorSignaturesComplete(signingRole)){$('sigMessage').textContent=signatureStepHint(signingRole);return;}const role=signingRole,previous=signatureData[role];await sequentialConfirm();if(signatureData[role]&&signatureData[role]!==previous){if(role==='recorder1'){delete signatureData.supervisor1;delete signatureData.approver;}else if(role==='recorder2'){delete signatureData.supervisor2;delete signatureData.approver;}else if(role==='supervisor1'||role==='supervisor2')delete signatureData.approver;renderSignatures();save();updateSigningGate();}};
roles.approver='ผู้รับรองการตรวจสอบ / หัวหน้าแผนก';$('approver').closest('.sigcard').querySelector('h3').textContent=roles.approver;
const gateLock=updateLock;updateLock=function(){gateLock();updateSigningGate();};
function showSignatureWaiting(){for(const id of Object.keys(roles)){const preview=$('preview_'+id);preview.querySelector('.waitingSignature')?.remove();if(signatureData[id]||priorSignaturesComplete(id))continue;const placeholder=preview.querySelector('span');if(placeholder){placeholder.style.flexDirection='column';placeholder.style.gap='8px';const message=document.createElement('strong');message.className='waitingSignature';message.style.cssText='color:#b42318;font-size:13px;text-align:center;line-height:1.5;padding:0 8px';message.textContent=signatureStepHint(id);placeholder.append(message);}}document.querySelectorAll('.stepHint').forEach(el=>el.hidden=true);}
const waitingGate=updateSigningGate;updateSigningGate=function(){waitingGate();showSignatureWaiting();};
const waitingRender=renderSignatures;renderSignatures=function(){waitingRender();showSignatureWaiting();};
document.addEventListener('input',updateSigningGate);
const demoCollect=collect;collect=function(){return {...demoCollect(),demo:demoMode};};
const demoApply=apply;apply=function(data){demoApply(data);demoMode=data.demo===true;demoNotice.hidden=!demoMode;updateSigningGate();};
function fillDemo(){if(isLocked())return;const centers=[5500,20,22,18,21,.05,65,450,220,85,87,55,58,41,48,29,33,57,59,40,1.1,1.15,.14,1.2,1.25,1.5];times.forEach((t,r)=>fields.forEach((f,c)=>{const base=centers[c];const change=c===5?.01:c===22?.001:c>=20?.01:c===0?10:1;const value=base+((r%5)-2)*change;$('v'+r+'_'+c).value=String(Number(value.toFixed(3)));check($('v'+r+'_'+c));}));$('date').value='2026-10-02';$('year').value=$('year').value||defaultYear()||'2569/2570';$('machine').value='DEMO-TURBINE-01';signatureData={};hourEvidence={};demoMode=true;demoNotice.hidden=false;currentHour=0;renderHour();renderSignatures();save();updateSigningGate();}
demoButton.onclick=()=>{if(confirm('กรอกตัวเลข Demo แทนข้อมูลเดิมทุกชั่วโมง และล้างลายเซ็น/หลักฐาน? ควรส่งออกข้อมูลสำรองก่อน'))fillDemo();};
const baseResetDemo=$('reset').onclick;$('reset').onclick=()=>{baseResetDemo();if($('status').textContent==='เริ่มบันทึกใหม่แล้ว'){demoMode=false;demoNotice.hidden=true;updateSigningGate();}};
try{const saved=localStorage.getItem(key);if(saved){demoMode=JSON.parse(saved).demo===true;demoNotice.hidden=!demoMode;}else if(!localStorage.getItem('ESC_TURBINE_DEMO_INITIALIZED')){fillDemo();localStorage.setItem('ESC_TURBINE_DEMO_INITIALIZED','1');}}catch{}
document.fonts.ready.then(()=>renderSignatures());updateSigningGate();

